title: Avery Pike
logo: "/images/R07A8955.jpg?raw=true"
description: > 
  Data Scientist
  <br><br>
  Data Analyst for the IRR Department at Chemeketa Community College.
  <a href="https://www.chemeketa.edu/faculty-staff/institutional-research/">Chemeketa Community College IRR Department</a>
  <br><br>
  BA in Philosophy, MS in Data Science from Willamette University
  <br><br>
  <a href="https://www.linkedin.com/in/avery-pike-5ab10b103/">View My LinkedIn Profile</a> 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

<p><a href="mailto:avery.pike@gmail.com">Personal Email: avery.pike@gmail.com</a></p>
<p><a href="mailto:apike5@chemeketa.edu">Work Email: apike5@chemeketa.edu</a></p>
